options:
  prev_tag: "versio-prev"

projects:
  - name: "yambler"
    root: "yambler"
    id: 1
    tag_prefix: "yambler"
    labels: cargo
    version:
      file: "Cargo.toml"
      toml: "package.version"
    hooks:
      post_write: 'cargo update --workspace'

  - name: "scripts"
    root: "scripts"
    id: 3
    tag_prefix: "scripts"
    version:
      tags:
        default: "0.0.0"

  - name: "install"
    root: "install"
    id: 2
    tag_prefix: "install"
    version:
      tags:
        default: "0.0.0"

sizes:
  use_angular: true
  fail: ["*"]
