name: 'versio-actions-install'
description: 'Install Versio'
author: 'Charlie Ozinga <ozchaz@gmail.com>'
branding:
  icon: play-circle
  color: black
inputs:
  version:
    description: 'Version of Versio to install, using Github release identifier, like "tags/TAG_NAME" or "RELEASE_ID"'
    required: false
    default: 'latest'

outputs:
  versio:
    description: Installed Versio version

runs:
  using: 'composite'
  steps:
    - run: |
        mkdir -p $HOME/bin
        echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
    - run: cp ${{ github.action_path }}/cargo-name $HOME/bin/cargo-name
      shell: bash
    - run: cp ${{ github.action_path }}/cargo-version $HOME/bin/cargo-version
      shell: bash
    - run: echo "versio=\"$(versio -V | cut -d' ' -f 2)\"" >> $GITHUB_OUTPUT
      shell: bash
