key: job-project-matrixes
value:
  runs-on: ubuntu-latest
  if: SNIPPET_not-skip-ci
  environment: publish
  env: SNIPPET_common-env
  outputs:
    cargo-matrix: ${{ steps.find-cargo-matrix.outputs.matrix }}
    all-matrix: ${{ steps.find-all-matrix.outputs.matrix }}
  steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get versio
      uses: chaaz/versio-actions/install@v1.2
    - name: Find cargo matrix
      id: find-cargo-matrix
      run: echo matrix={\"include\":$(versio -l none info -l cargo -R -N)} >> $GITHUB_OUTPUT
    - name: Find all matrix
      id: find-all-matrix
      run: echo matrix={\"include\":$(versio -l none info -a -R -N)} >> $GITHUB_OUTPUT
