key: job-publish-bins
value:
  needs: github-publish
  strategy:
    matrix:
      include:
        - os: ubuntu-latest
          target: 'x86_64-unknown-linux-gnu'
          root: 'yambler'
          rustflags: '-D warnings -C link-args=-s'
          bin_name: 'yambler'
        - os: macos-latest
          target: 'x86_64-apple-darwin'
          root: 'yambler'
          rustflags: '-D warnings'
          bin_name: 'yambler'
        - os: windows-latest
          target: 'x86_64-pc-win32.exe'
          root: 'yambler'
          rustflags: '-D warnings'
          bin_name: 'yambler.exe'
  if: SNIPPET_not-skip-ci
  environment: publish
  env: SNIPPET_common-env
  runs-on: ${{ matrix.os }}
  steps:
    - name: Checkout release
      uses: actions/checkout@v3
      with:
        ref: main
    - SNIPPET_get-cargo
    - name: Build binary
      run: cargo build --release
      working-directory: ${{ matrix.root }}
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.github-publish.outputs.upload_url }}
        asset_path: ${{ matrix.root }}/target/release/${{ matrix.bin_name }}
        asset_name: yambler__${{ matrix.target }}
        asset_content_type: application/octet-stream
