key: job-versio-release
value:
  needs:
    - cargo-checks
    - versio-checks
  runs-on: ubuntu-latest
  if: SNIPPET_not-skip-ci
  environment: publish
  env: SNIPPET_common-env
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get versio
      uses: chaaz/versio-actions/install@v1.2
    - SNIPPET_get-cargo-minimal
    - name: Fetch history
      run: git fetch --unshallow
    - name: Generate release
      run: versio release
