key: steps-github-publish
value:
  - name: Checkout release
    uses: actions/checkout@v2
    with:
      ref: main
  - name: Get versio
    uses: chaaz/versio-actions/install@v1.2
  - name: Find version
    id: find-version
    run: echo "version=\"$(versio -l none info -i 1 -F | jq -r ''.[0].full_version'')\"" >> $GITHUB_OUTPUT
  - name: Publish to GitHub
    id: publish-to-github
    uses: actions/create-release@v1
    with:
      tag_name: ${{ steps.find-version.outputs.version }}
      release_name: (TODO) RELEASE FOR ${{ steps.find-version.outputs.version }}
      body: |
        (TODO) SUMMARY
        - (TODO) FEATURE1

        New to the Yambler? The [repository](https://github.com/chaaz/versio-actions/tree/main/yambler) is the best place to learn about the Yambler and what it can do. If you want to report a bug or request a feature, you can do so at our [Issues](https://github.com/chaaz/versio-actions/issues) link, but we ask you first read the [Troubleshooting](https://github.com/chaaz/versio-actions/blob/main/docs/troubleshooting.md) page learn about problems and their solutions.

        To install, follow the instructions for your platform; some files might be zipped for improved download speed. For example, on MacOS you can do something like this (assuming `~/bin` exists and is in your PATH):

        ```sh
        curl -L https://github.com/chaaz/versio-actions/releases/download/${{ steps.find-version.outputs.version }}/yambler__x86_64-apple-darwin -o ~/bin/yambler
        chmod +x ~/bin/yambler
        ```

        **MacOS:** download `yambler__x86_64-apple-darwin`, copy to `yambler` in your PATH.
        **GNU Linux 64:** download `yambler__x86_64-unknown-linux-gnu`, copy to `yambler` in your PATH.
        **Windows:** download `yambler__x86_64-pc-win32.exe`, copy to `yambler.exe` in your %PATH.
      draft: true
      prerelease: false
      commitish: main
